// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.media.autoplay.default", 1);
user_pref("app.normandy.user_id", "20d1003d-0847-40f9-abbb-fc4932d8cc43");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1558027553);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1558027673);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1558031225);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1558027313);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1558013571);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1558027433);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1558028994);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1558028874);
user_pref("browser.bookmarks.editDialog.confirmationHintShowCount", 3);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 860160);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1558013420);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.impressionId", "{3ac4e300-a44b-430a-9795-a56c8dc225eb}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1557957600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1558031206663");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1558032990663");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1558031237490");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1558034837490");
user_pref("browser.search.region", "CZ");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190507231222");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1558031293");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage", "http://a-fs.cz/fedora-29-mate-pro-nevidome/");
user_pref("browser.startup.homepage_override.buildID", "20190507231222");
user_pref("browser.startup.homepage_override.mstone", "66.0.5");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1558013422781");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.fedora.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "66.0.5");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.blocklist.lastModified", "Tue, 14 May 2019 22:00:28 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 30);
user_pref("extensions.getAddons.cache.lastUpdate", 1558027553);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190507231222");
user_pref("extensions.lastAppVersion", "66.0.5");
user_pref("extensions.lastPlatformVersion", "66.0.5");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{b294ade6-36a7-4c4c-a481-aebae9cd55f6}\",\"addons\":{\"baidu-code-update@mozillaonline.com\":{\"version\":\"2.66\"},\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"2e54ade8-01e6-46be-b1a2-7f85989864cb\",\"screenshots@mozilla.org\":\"ee6f2d17-93c6-4325-b3a9-6e5c4a1e19a2\",\"webcompat-reporter@mozilla.org\":\"f9478897-a10b-4987-a0b8-427605c1eb5b\",\"webcompat@mozilla.org\":\"1d70ab7c-5aee-474a-a9a1-2ee4c65cb794\",\"baidu-code-update@mozillaonline.com\":\"ce7bbb75-62de-42eb-b778-85716fb757ad\",\"fxmonitor@mozilla.org\":\"2c2e86e4-363e-40fa-98c3-9c10c0d049fd\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-manager.buildID", "20190508134636");
user_pref("media.gmp-manager.lastCheck", 1558013609);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("security.sandbox.content.tempDirSuffix", "a7f0785f-75ea-479e-a325-aaa0bbc4b4ad");
user_pref("security.sandbox.plugin.tempDirSuffix", "364427bf-8680-410a-9c80-5677b1cbe301");
user_pref("services.blocklist.addons.checked", 1558027651);
user_pref("services.blocklist.gfx.checked", 1558027651);
user_pref("services.blocklist.onecrl.checked", 1558027651);
user_pref("services.blocklist.pinning.checked", 1558027651);
user_pref("services.blocklist.plugins.checked", 1558027651);
user_pref("services.settings.clock_skew_seconds", -219);
user_pref("services.settings.last_update_seconds", 1558027651);
user_pref("services.settings.main.language-dictionaries.last_check", 1558027651);
user_pref("services.settings.main.onboarding.last_check", 1558027651);
user_pref("services.settings.main.sites-classification.last_check", 1558027651);
user_pref("services.settings.main.tippytop.last_check", 1558027651);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1558031286);
user_pref("toolkit.telemetry.cachedClientID", "bda989ab-79b4-4d31-ace0-f26f0439f66f");
user_pref("toolkit.telemetry.previousBuildID", "20190507231222");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
